apiVersion: v1
kind: Namespace
metadata:
  name: formation-lap

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve-app
  namespace: formation-lap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eve-app
  template:
    metadata:
      labels:
        app: eve-app
    spec:
      containers:
        - name: eve-container
          image: maxjagger0508/eve-app:4199563
          ports:
            - containerPort: 8080
