apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment/formation-user-deployment.yaml
  - deployment/formation-search-deployment.yaml
  - deployment/formation-video-deployment.yaml
  - services/formation-user-service.yaml
  - services/formation-search-service.yaml
  - services/formation-video-service.yaml

