apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: user-service
    newName: 404457776061.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
    newTag: "init"
  - name: order-service
    newName: 404457776061.dkr.ecr.ap-northeast-2.amazonaws.com/order-service
    newTag: "init"
  - name: product-service
    newName: 404457776061.dkr.ecr.ap-northeast-2.amazonaws.com/product-service
    newTag: "init"

