apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-user
  namespace: formation-lap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formation-user
  template:
    metadata:
      labels:
        app: formation-user
    spec:
      containers:
        - name: formation-user
          image: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/formation-user:latest
          ports:
            - containerPort: 8000
          env:
            - name: OTEL_SERVICE_NAME
              value: "formation-user"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "alloy-seoul-otlp.app-monitoring-seoul.svc.cluster.local:4317"

