apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-video
  namespace: formation-lap
spec:
  replicas: 4
  selector:
    matchLabels:
      app: formation-video
  template:
    metadata:
      labels:
        app: formation-video
    spec:
      containers:
        - name: formation-video
          image: 978285406261.dkr.ecr.ap-northeast-2.amazonaws.com/formation-video:a9c801f284209622eef1dc8f243e5e09465664ea
          ports:
            - containerPort: 8000
          env:
            - name: OTEL_SERVICE_NAME
              value: "formation-video"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "alloy-seoul-otlp.app-monitoring-seoul.svc.cluster.local:4317"
